[tox]
envlist = py39-{lint,invalidcode},py39-black-{run,check}

[testenv]
skip_install=True
deps =
  py39-{lint,invalidcode}: flake8
  py39-black-{run,check}: black
  py39-mypy: mypy >= 0.900
  
# Linting environment
# Mise en place de de l'environnement
[testenv:py39-lint]
description = "Run flake8 for linting"
commands = 
        flake8 src doc maintenance tests --ignore E402,E501,E203,W503,E741 --exclude src/tests,src/vendor

# Invalid code detection environment
# Environnement de détection de codes invalides
[testenv:py39-invalidcode]
description = "Detect invalid code patterns using flake8"
commands =
        flake8 src bin maintenance --exclude src/tests,src/vendor --select F,E722,W605

# Black formatting environments
# Environnement de formatage 
[testenv:py39-black]
description = "Automatically format code with black"
commands =
         black --check --diff bin src doc maintenance tests


[testenv:py39-black-check]
description = "Check code formatting with black (without modifying files)"
commands =
         black bin src doc maintenance tests

# Type checking with mypy
# Vérifications des données avec mypy
[testenv:py39-mypy]
description = "Static type checking using mypy"
commands =          
         mypy  --ignore-missing-import --install-types --non-interactive --follow-imports silent src/ --exclude (acme_tiny|migrations|tests)
